# Generated by Django 4.2.6 on 2023-10-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Людина', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команди'},
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ім`я'),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='people',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Назва команди'),
        ),
    ]
